SHARED_COLLECTION_NAME = "class_content_embeddings"
EMBEDDING_MODEL_NAME = "gemini-embedding-001"
EMBEDDING_VECTOR_SIZE = 768
EMBEDDING_DOCUMENT_TASK_TYPE = "RETRIEVAL_DOCUMENT"
EMBEDDING_QUERY_TASK_TYPE = "RETRIEVAL_QUERY"
VIDEO_TRANSCRIPTS_PREFIX = "transcripts/videos"
